name: Develop workflow

on:
  push:
    branches: [ develop ]
    paths:
      - 'src/**'
      - 'pom.xml'
  workflow_dispatch:

env:
  IMAGE_NAME: books-reviewer

jobs:
  test-and-publish:
    name: Build Java application and run test
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run unitary test
      run: mvn -B -Dtest=*UnitaryTest test
    - name: Run REST test
      run: mvn -B -Dtest=*RestTest test
    - name: Run e2e test
      run: mvn -B -Dtest=*SeleniumTest test
    - name: Generate tag
      run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_OUTPUT
      id: project
    - name: Build image
      run: mvn spring-boot:build-image -DskipTests -Dspring-boot.build-image.imageName=$IMAGE_NAME
    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
    - name: Push image to DockerHub
      run: |
        docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.project.outputs.tag }}-dev
        docker tag $IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:dev
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME --all-tags
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to Github Container Registry
      run: |
        IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
        docker tag $IMAGE_NAME ghcr.io/$IMAGE_USER/$IMAGE_NAME:${{ steps.project.outputs.tag }}-dev
        docker tag $IMAGE_NAME ghcr.io/$IMAGE_USER/$IMAGE_NAME:dev
        docker push ghcr.io/$IMAGE_USER/$IMAGE_NAME --all-tags