name: Master workflow

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
 IMAGE_NAME: books-reviewer

jobs:

  publish-docker:
    name: Publish Docker image to DockerHub and GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Generate tag
      run: echo "tag=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout | sed 's/\.RC.*//g' )" >> $GITHUB_OUTPUT
      id: project
    - name: Login to DockerHub
      run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
    - name: Pull image from DockerHub
      run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:rc
    - name: Run application
      run: docker run --rm -d --name $IMAGE_NAME-test -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:rc
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run REST test over Docker application
      run: mvn -B -Dtest=RestTest -Dport=8080 test
    - name: Run e2e test over Docker application
      run: mvn -B -Dtest=SeleniumTest -Dport=8080 test
    - name: Stop application
      run: docker stop $IMAGE_NAME-test
    - name: Push image to DockerHub
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:rc ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.project.outputs.tag }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ steps.project.outputs.tag }}
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Push image to Github Container Registry
      run: |
        IMAGE_USER=$(echo ${{ github.repository_owner }} | awk '{print tolower($0)}')
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:rc ghcr.io/$IMAGE_USER/$IMAGE_NAME:${{ steps.project.outputs.tag }}
        docker push ghcr.io/$IMAGE_USER/$IMAGE_NAME:${{ steps.project.outputs.tag }}